### ISSUE TITLE
Installation on a web hosting

### ISSUE THREAD

**Issue by robertripoll** [Taronyuu/Teamspeak3-server-manager#1]
Hi,

I'm trying to install the control panel on a Linux web hosting, but since it's a standard web hosting, I cannot access the console or perform commands via the terminal. Is there a way I can install this control panel without having to touch any command line?

PD: I already know how to install _Composer_ manually.

Good work and thanks in advance.

**Comment by Taronyuu** [comment]
You can install it local (or on any other device where you do have composer and php) and upload everything (including the vendor folder) to your webhosting. Don't forget to migrate, export and import your database.
