### ISSUE TITLE
More Configurable options

### ISSUE THREAD

**Issue by KFC4Life** [Taronyuu/Teamspeak3-server-manager#12]
When I create/edit an server I can't configure things like the server port.
Maybe you can add forms such as:
- Server port
- Server password

**Comment by Cannonb4ll** [comment]
- Server port: Why do you want this?
- Server password: Is already available.

**Comment by KFC4Life** [comment]
Server port is very helpfull when you want to run more TeamSpeak servers.

**Comment by Taronyuu** [comment]
However, the ports are already incremented when created? So there is no need for this?

**Comment by KFC4Life** [comment]
I'm thinking its very usefull, for example if you want to redirect users from an old TeamSpeak server to a new one.
