### ISSUE TITLE
Custom error pages

### ISSUE THREAD

**Issue by KFC4Life** [Taronyuu/Teamspeak3-server-manager#13]
Can you add custom error pages?
When there is an error I get pages like this:
https://gyazo.com/e0bbf4199e4854b697ecbff128a8fcd5

**Comment by Taronyuu** [comment]
You can set the `APP_DEBUG` value to false in your `.env` file so it doesn't show the stacktrace. Still not really custom but it should be a bit better already. 😄

**Comment by Taronyuu** [comment]
Fixed by @Cannonb4ll (#13)
