### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by senseiriksha** [Taronyuu/Teamspeak3-server-manager#14]
Hi,

I tried to install your panel and when I executed composer install, at the end of install process I got this error:
php_network_getaddresses: getaddrinfo failed: Name or service not known
Do you know where is the problem ?
http://prntscr.com/dd5roi

Thanks!

**Comment by Taronyuu** [comment]
Did you execute this step? `Set the required values in the .env file. You can copy them from the .env.example file. (Create the .env file if it does not exist by copying the .env.example file)` 

If so, are you 100% percent sure the credentials are correct and your query port is open to the internet.

**Comment by senseiriksha** [comment]
Am I doing it right ?
http://prntscr.com/dd734g

**Comment by Taronyuu** [comment]
Is your Teamspeak server hosted on your local box?

**Comment by senseiriksha** [comment]
My Teamspeak 3 server is hosted on shared VPS server and this control panel is hosted on VPS aswell.

**Comment by Taronyuu** [comment]
So are they on the same server or not?

**Comment by senseiriksha** [comment]
Yes they are.

**Comment by Taronyuu** [comment]
I'm almost certain that you are using the wrong ip/port, that or you are using a separate firewall.

In anyway, the panel is unable to connect to your TS3 server instance.
