### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by xAzz** [Taronyuu/Teamspeak3-server-manager#17]
Need help on how to install -- New to linux, dont understand many commands,,

**Comment by Taronyuu** [comment]
This isn't really helpful, what exactly isn't working?

**Comment by xAzz** [comment]
I dont understand how to install it

**Comment by Taronyuu** [comment]
Best thing to do is ask someone that is able to understand it to help you. :) This isn't the place for installation request unless it is something that is wrong with the panel.
