### ISSUE TITLE
Channel management

### ISSUE THREAD

**Issue by Cannonb4ll** [Taronyuu/Teamspeak3-server-manager#23]
Ability to manage all the channels.

**Comment by bbashy** [comment]
I run a large public TS server and I want to be able to manage the channels in terms of setting permanent from temp and maybe display when someone last used a channel.

Would it be possible with the TS API to do any of that?

**Comment by Cannonb4ll** [comment]
I think it is possible, I just started on channel management in this panel and have not figured out al the possibilities yet.
