### ISSUE TITLE
Upgrading to 5.5 when it's out?

### ISSUE THREAD

**Issue by bbashy** [Taronyuu/Teamspeak3-server-manager#24]
Just wondering if you'll be upgrading to 5.5 LTS when it's out?

**Comment by Cannonb4ll** [comment]
Why would you be needing this really?

**Comment by bbashy** [comment]
Just because it would of been 2 years since release (June 9, 2015), thus not receiving bug fixes.

I can do the upgrade and submit a PR but just asking if you're planning on doing it.

**Comment by Cannonb4ll** [comment]
There are no real plans to upgrade to 5.5 when its out. Sincerely this is still on 5.1 we could of upgrade to 5.4 as well.

If you are willing to create a PR to upgrade to 5.5 please do so! You will only help us 👍

**Comment by bbashy** [comment]
OK, I'll add a note to do it upon release.

Thanks.

**Comment by Taronyuu** [comment]
@Cannonb4ll, remember that 5.5 is a LTS release. This is also the reason why I haven't upgraded from 5.1 yet. 😄

**Comment by Cannonb4ll** [comment]
🥇

**Comment by bbashy** [comment]
Will try work on this over the next few days :+1:

**Comment by Cannonb4ll** [comment]
Awesome 👍

**Comment by Taronyuu** [comment]
Almost forgot about that, shouldn't be that hard I think. 

Good to hear 😄

**Comment by bbashy** [comment]
I kinda re-built it in Laravel 5.5 and Bootstrap 4. Will push and open PR soon™

![](https://d.pr/i/IzdBur/3Ho7JVwf.jpg)

**Comment by bbashy** [comment]
So I've got a working version and I've added a branch on my fork.

https://github.com/bbashy/Teamspeak3-server-manager/tree/laravel55

Check it out and I guess maybe a new branch for it? Not sure how to merge a new branch without history.

**Comment by Taronyuu** [comment]
Can you create a pull request for those changes? They look really awesome 😄 

After that I'll create a new branch in this repository, merge it and rebase the master on that branch.

**Comment by bbashy** [comment]
@Taronyuu I created an orphan branch so I can't PR them into master since it's totally different histories.

Shall I just get the files and delete all and replace from a normal branch checkout?

**Comment by bbashy** [comment]
#31 has been merged so this is now closed.
