### ISSUE TITLE
I have a Problem

### ISSUE THREAD

**Issue by 11037luna** [Taronyuu/Teamspeak3-server-manager#29]
At the time of installation when I have to do `

> $ php artisan teamspeak: reset

` it puts me:
```

   [PDOException]
   SQLSTATE [HY000] [14] unable to open database file

```
I have done everything right ...

**Comment by Taronyuu** [comment]
Are you entirely sure you've done this step?

```Create an empty file named database.sqlite in the storage folder. (so storage/database.sqlite). If you are on Linux use touch storage/database.sqlite.```

Sounds like the database file does not exists. What OS are you on?

**Comment by 11037luna** [comment]
Linux Debian 8

**Comment by Taronyuu** [comment]
Can you show me the output of `ls -al ./storage`? Ran from the root of the project. (Where your `.env` file is located)

I'm pretty sure the database is not or incorrectly created.

**Comment by Taronyuu** [comment]
Closed since no reply has been given.
