### ISSUE TITLE
no install directory

### ISSUE THREAD

**Issue by furest** [Taronyuu/Teamspeak3-server-manager#30]
Hello there,
I just followed the installation tutorial (no error whatsoever)
However it seems like the install directory hasn't been created.
I try to access to the interface (mydomain.tld/ts3sm/install. I installed it in a subdirectory) but it doesn't exist at all.
Have I missed something?
EDIT: spelling

**Comment by Taronyuu** [comment]
What kind of webserver are you using? .htaccess should be enabled for that directory and the directory should point to `public/index.php`.

**Comment by furest** [comment]
I'm actually trying to reinstall it with my domain name as the url.
I'm using apache 2.4 on debian 8.
.htaccess is enabled but there's none in the git right?
EDIT: I have reinstalled but it still doesn't work

**Comment by furest** [comment]
up? :)

**Comment by Taronyuu** [comment]
There is no .htaccess in the root indeed, it is located in the public folder. 

Your webserver should be configured to use the `public`  folder as your webroot. 

Depending on the exact setup of your webserver you can either configure Apache correctly (https://www.howtoforge.com/tutorial/install-laravel-on-ubuntu-for-apache/) or may be able to symlink the `public` folder to your actual webroot.
