### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by ghost** [Taronyuu/Teamspeak3-server-manager#32]
I don't understand where upload file in lavarel, I ulpload in /blog ?

**Comment by KFC4Life** [comment]
Upload it on your webserver and make sure your web server's document root is the public folder.

**Comment by ghost** [comment]
I have to install the files in / blog / public?

**Comment by Taronyuu** [comment]
Hi,

We really need some more info on what webserver/hosting/panel you are using. I'd recommend you to reach out to someone professional that is able to help you set this panel up.

If you have more information or any specific error that is happening, feel free to reopen this issue 😄

**Comment by ghost** [comment]
I explain to you. I installed LAVAREL but I do not know where to put the panel on the server should I put it in / var / www / html or / blog / public?
For info I used Debian 9.
Thanks
