### ISSUE TITLE
Message a teamspeak user

### ISSUE THREAD

**Issue by belzaaron** [Taronyuu/Teamspeak3-server-manager#33]
Hello! I was wondering if you could possibly try to implement a feature that will allow us to enter in an id of a user and send them a private message?
Thanks and great work so far!

**Comment by Cannonb4ll** [comment]
You ment sent a message to the user inside the teamspeak server?

**Comment by belzaaron** [comment]
Yes! Exactly!

**Comment by Taronyuu** [comment]
Why close the issue? This would be a nice enhancement if someone has the time to pick it up. :)

**Comment by belzaaron** [comment]
My bad, I thought that since I have no time right now to implement this myself, I figured I don't want to drag the repo down.

**Comment by Taronyuu** [comment]
No worries, I'm hoping for someone that has the time wants to implement this. Otherwise an issue tracker with only 'enhancement' issues shouldn't be a problem.

**Comment by Cannonb4ll** [comment]
Picking this issue up atm.

**Comment by Cannonb4ll** [comment]
Should be possible now @belzaaron, can you have a check on if this is what you anticipated?
