### ISSUE TITLE
error at "php artisan migrate"

### ISSUE THREAD

**Issue by Benimautner** [Taronyuu/Teamspeak3-server-manager#35]
When I type in the command "php artisan migrate" like the installation says, i get that:

```
In Connection.php line 664:
                                                                               
  Database (main) does not exist. (SQL: select * from sqlite_master where typ  
  e = 'table' and name = migrations)                                           
                                                                               

In SQLiteConnector.php line 34:
                                   
  Database (main) does not exist.  
```
                                   
I'm pretty new to sqlite, so I don't know what to do. Please help me.

**Comment by bbashy** [comment]
What database settings did you enter into .env? Did you create the sqlite file first as per install instructions?

**Comment by Benimautner** [comment]
I did enter
```
DB_CONNECTION=sqlite
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=main
DB_USERNAME=root
DB_PASSWORD=supersecretpassword

```
Into my .env and created the database like in the instructions.

**Comment by bbashy** [comment]
Ok, that's the problem. With `sqlite` connection, you don't need anything else. `DB_DATABASE` becomes the sqlite file path instead :) (check `config/database.php`)

Remove all but `DB_CONNECTION=sqlite` and it should be fine.

**Comment by Benimautner** [comment]
Now there's a different Error.

```
In Connection.php line 664:
                                                                                    
  could not find driver (SQL: select * from sqlite_master where type = 'table' and  
   name = migrations)                                                               
                                                                                    

In Connector.php line 67:
                         
  could not find driver  
                         


```

**Comment by bbashy** [comment]
Sounds like you need the actual sqlite driver so PHP can talk to it.

on macOS, this would be something like;
```
brew install sqlite
```

**Comment by Benimautner** [comment]
I`m on Linux so I installed it with

```
apt-get Install sqlite
```


When I Type in 
```
sqlite
```

 then there comes:

```
sqlite
SQLite version 2.8.17
Enter ".help" for instructions

```

I'm not 100% sure if thats the newest Version of sqlite but i think so...

**Comment by bbashy** [comment]
Yeah that won't matter. Looking good. Try run migrations again and see what you get.

**Comment by Taronyuu** [comment]
@bbashy thanks for helping! 

Its been 4 days so I'm going to close this. If you still have issues please let me/us know. 👍
