### ISSUE TITLE
Sql Error "php artisan migrate"

### ISSUE THREAD

**Issue by FurkanGezek** [Taronyuu/Teamspeak3-server-manager#37]
[Illuminate\Database\QueryException]
  SQLSTATE[HY000] [14] unable to open database file (SQL: selec
  t * from sqlite_master where type = 'table' and name = migrat
  ions)

  [PDOException]
  SQLSTATE[HY000] [14] unable to open database file

**Comment by bbashy** [comment]
Did you create the sqlite database file from the instructions? Did you remove the DB_DATABASE entry from .env? Since you're using sqlite, you'll want to remove that as it overrides the sqlite file path.

**Comment by FurkanGezek** [comment]
ENV FİLE

APP_NAME=Laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://SANSURED!!
APP_TIMEZONE="UTC"

DB_CONNECTION=sqlite
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=panel
DB_USERNAME=tspanel
DB_PASSWORD=190755Fb-

TS_USERNAME=serveradmin
TS_PASSWORD=SANSURED!!
TS_SERVER_IP=SANSURED!!
TS_SERVER_PORT=10011

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=localhost
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=

**Comment by FurkanGezek** [comment]
I solved the problem I changed the DB_CONNECTION value to MySQL

**Comment by bbashy** [comment]
You just remove the other options (they're not needed for sqlite).

Remove these (or comment with hash).
```
DB_HOST=
DB_PORT=
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=
```

You should just have this if you want to use sqlite.
```
DB_CONNECTION=sqlite
```
