### ISSUE TITLE
Failed to parse address ":"

### ISSUE THREAD

**Issue by ivofacundo** [Taronyuu/Teamspeak3-server-manager#41]
Hello when i fully installed the poryect and generate the key for the app, i cant run php artisan serve, but i can still enter with the /public folder, buti i still got the error

**Failed to parse address ":"**

![image](https://user-images.githubusercontent.com/13089746/43682722-4e207a64-9853-11e8-8dff-095e3c007ac0.png)

**Comment by Taronyuu** [comment]
Can you post the contents of your `.env` *without the password(s)*?

**Comment by ivofacundo** [comment]
I tried to install the panel again and it worked correctly, I could not explain what the error was, a thousand apologies, I will also open another issue because I have another error now when connecting with the server.

**Comment by Taronyuu** [comment]
No worries, glad it is working as expected now. 😄
