### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by jesseke55** [Taronyuu/Teamspeak3-server-manager#5]
I did composer install and get this error:

> php artisan clear-compiled

  [TeamSpeak3_Transport_Exception]
  Failed to parse address ":"

Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output:

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by Taronyuu** [comment]
Can you try follow the next step. (fill your .env file with the correct values) and after that run `composer install`. 

If that works you can continue with the other steps. Please let me know. 😄

**Comment by dm94** [comment]
I feel the same, I did what you said and I get the same error
