### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by DasClarky** [Taronyuu/Teamspeak3-server-manager#7]
> php artisan clear-compiled

  [TeamSpeak3_Transport_Exception]
  Failed to parse address ":"

Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output:

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

Not sure what happened here

**Comment by Alphakilo** [comment]
Got the same error.
Ubuntu 16.04, nginx + PHP 7.0

Cloned the repo:
`git clone https://github.com/Taronyuu/Teamspeak3-server-manager.git`
`composer install`

```
Generating autoload files
> php artisan clear-compiled


  [TeamSpeak3_Transport_Exception]  
  Failed to parse address ":"       


Script php artisan clear-compiled handling the post-install-cmd event returned with an error


  [RuntimeException]  
  Error Output:       


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

Full output over here:
https://gist.github.com/Alphakilo/ae3ef000bcf0043722e1a4d879b1d26b

**Comment by Taronyuu** [comment]
Please try to do the next step (create/and fill in the .env file) and after that run `composer install`. I updated the readme file so you can also follow that.

Let me know. :)

**Comment by DasClarky** [comment]
Ahh thanks for updating the wiki and the hard work making this, i will play later now i know what i am doing :+1:

**Comment by hydrouk** [comment]
What shout the .env file be called? i got the same error even after making a .env file named server.env?

**Comment by Alphakilo** [comment]
@hydrouk Just `.env`
Files with names preceded by a `.` are "hidden" in Unix-like OSes.

**Comment by DasClarky** [comment]
I had to delete that, what a spanner i am, no admin while drinking i think
