### ISSUE TITLE
[TeamSpeak3_Transport_Exception] Connection timed out

### ISSUE THREAD

**Issue by ChocoboMaster** [Taronyuu/Teamspeak3-server-manager#8]
Hi Taronyuu, Awesome work looks promising!
Let me start of by saying that I am very unfamiliar with Composer...

Here is the issue; I keep getting 

> [TeamSpeak3_Transport_Exception] Connection timed out

whenever I try to execute a command. (composer install, php artisan migrate...)

Same error on my main computer and on a brand new vm. (Running LAMP on Ubuntu 16.04)
What am I doing wrong?
Best regards,
ChocoboMaster

**Update:** This is when I'm trying to run it over the network. On the same network, all ports open. I can ping the ts3 server machine and use another ServerQuery library without problems.

**Comment by Taronyuu** [comment]
Did you add yourself in the whitelist file for your Teamspeak server? `query_ip_whitelist.txt`

**Comment by Taronyuu** [comment]
Closing this until a reply or update has been given.

**Comment by Taronyuu** [comment]
Closing this until a reply or update has been given.
