### ISSUE TITLE
[TeamSpeak3_Transport_Exception]

### ISSUE THREAD

**Issue by TJBK** [Taronyuu/Teamspeak3-server-manager#9]
Okay I have no idea about composer.

But any way when I run `composer install` this is what I get:

![Image of CML](https://my.mixtape.moe/pdtrub.png)

So yeah I'm not to sure what happened

**Comment by Taronyuu** [comment]
Show me the contents of your .env file. (Please remove any sensitive info like passwords)

**Comment by TJBK** [comment]
Sorry I worked out what was wrong. It was because one of the password I had included a forward slash in it.

Edit: Fix grammar
